application: missile-launch-bb06a
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest

- name: ssl
  version: latest
